### ISSUE TITLE
errors occur when importing objectives and pymc3

### ISSUE THREAD

**Issue by Spheluo** [ericmjl/flu-sequence-predictor#2]
Dear @ericmjl :
We would like to use the forecaster as Covid-19 forecaster. However, when I ran the codes in flu-forecaster with jupyter notebook, some errors occurred:
1. from keras import objectives
ImportError: cannot import name 'objectives' from 'keras'
2. import pymc3 as pm
AttributeError: 'TheanoConfigParser' object has no attribute 'gcc__cxxflags'
I have no idea what's wrong with it and don't know how to fix it.

**Comment by ericmjl** [comment]
@Spheluo this is a pretty old codebase and I wouldn't recommend using it anymore. Thanks for your interest, though.

**Comment by watercyn** [comment]
Dear @ericmjl :
it is such a pity to know that you personally do not recommend to use this codebase, as we found that the visualization of the forecaster helps illustrate the flu development in an effective and easily understanding manner. May i know you have other recommendation of similar codebase of newer version or more updated codebase for similar forecaster purpose?

**Comment by ericmjl** [comment]
Hi @watercyn! Much agreed, it is a pity as I don't have the time to keep it up-to-date anymore. 

More modern efforts at doing flu sequence forecasting include those by:

1. Eli Weinstein (Debora Marks' lab at Harvard Medical School): http://proceedings.mlr.press/v139/weinstein21a.html
2. Brian Hie's Evolocity: https://github.com/brianhie/evolocity

Each have their own assumptions, so be sure to consider that too :).
